feat: support Bash 4.4+ => 4.0+

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,17 +1,21 @@
 #!/usr/bin/env bash
+# Supported Bash: 4.0+
 
 set -o errexit
 set -o nounset
 set -o pipefail
-shopt -s inherit_errexit
+(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit
 [[ -n "${VERBOSE:+x}" ]] && set -o verbose
 [[ -n "${DEBUG:-}" ]] && IS_DEBUG=true || IS_DEBUG=false
 
 readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
 
+# shellcheck source=./tools/colors.bash
+source "$SCRIPT_DIR/tools/colors.bash"
 # shellcheck source=./src/load_internals.bash
 source "$SCRIPT_DIR/src/load_internals.bash"
-_lobash.imports ask
+_lobash.import_internals module_meta
+_lobash.imports ask choose
 
 is_valid_lobash_prefix() {
   local prefix=$1
@@ -21,6 +25,38 @@ is_valid_lobash_prefix() {
   [[ ${prefix%%_}_ == "$prefix" ]] && return 0
 
   return 1
+}
+
+init_bash_min_version() {
+  if [[ -n ${BASHVER:-} ]]; then
+    BASH_MIN_VERSION=$BASHVER
+    echo -e "${GREY}Build Lobash for Bash ${BASH_MIN_VERSION}+${RESET_ALL}"
+    return
+  fi
+
+  local use_defualt
+  set +e
+  read -r -d '' text <<EOF
+Default to generate Lobash for Bash 4.4+.
+If you want to run Lobash with lower-version Bash, enter "NO".
+Use Lobash for Bash 4.4+?
+EOF
+  set -e
+  use_defualt=$(l.ask "$text")
+
+  if [[ $use_defualt == YES ]]; then
+    BASH_MIN_VERSION=4.4
+    echo -e "${GREY}YES. Build Lobash for Bash ${BASH_MIN_VERSION}+${RESET_ALL}"
+  elif [[ $use_defualt == NO ]]; then
+    echo -e "${GREY}NO.${RESET_ALL}"
+    echo "Choose the minimum version of Bash in which Lobash will run:"
+    local supported_bash_verisons=( 4.0 4.1 4.2 4.3 4.4 )
+    BASH_MIN_VERSION=$(l.choose "${supported_bash_verisons[@]}")
+    echo -e "${GREY}Build Lobash for Bash ${BASH_MIN_VERSION}+${RESET_ALL}"
+  else
+    echo "Process terminated. Please enter YES or NO." >&2
+    return 4
+  fi
 }
 
 init() {
@@ -34,13 +70,15 @@ init() {
     fi
   fi
 
+  init_bash_min_version
+
   mkdir -p "$(dirname "$TARGET")"
 
   PREFIX=${PREFIX:-l.}
   OVERWRITE=${OVERWRITE:-no}
 
   if ! is_valid_lobash_prefix "$PREFIX"; then
-    echo "Invalid PREFIX=\"$PREFIX\". PREFIX must end with one of '_', '-', '.'" >&2
+    echo -e "${RED}Invalid PREFIX=\"$PREFIX\". PREFIX must end with one of '_', '-', '.'${RESET_ALL}" >&2
     return 4
   fi
 
@@ -70,7 +108,7 @@ clean() {
   if [[ $OVERWRITE != yes ]] && [[ -f $TARGET ]]; then
     local answer
     answer=$(l.ask "Existed file: ${TARGET}. Overwrite it?" N)
-    echo "$answer"
+    echo -e "${GREY}$answer${RESET_ALL}"
     case $answer in
       YES )
         ;;
@@ -112,42 +150,153 @@ fwrite() {
     >> "$TARGET"
 }
 
+semver_compare() {
+  local info_a info_b
+  IFS='.' info_a=( $1 )
+  IFS='.' info_b=( $2 )
+
+  # result=$(( info_a[0] - info_b[0] ))
+  if (( info_a[0] < info_b[0] )); then
+    echo -1
+  elif (( info_a[0] > info_b[0] )); then
+    echo 1
+  else
+    if (( info_a[1] < info_b[1] )); then
+      echo -1
+    elif (( info_a[1] > info_b[1] )); then
+      echo 1
+    else
+      echo 0
+    fi
+  fi
+}
+
+scan_metadata() {
+  local path=$1
+  local -a deps
+  local -A map
+  local module_name
+  module_name=$(basename "$path" .bash)
+
+  # Check the module scanned
+  [[ -n $(_lobash.get_module_metadata "$module_name" Module) ]] && return
+
+  module_names+=("$module_name")
+  _lobash.scan_module_metadata "$module_name"
+
+  compare=$(semver_compare "$BASH_MIN_VERSION" "${map[Bash]}")
+  if (( compare < 0 )); then
+    metadatas[${module_name}_skip]=true
+    metadatas[${module_name}_bash]="${map[Bash]}"
+  else
+    if [[ -n ${map[Dependent]:-} ]]; then
+      IFS=',' deps=( ${map[Dependent]} )
+
+      local dep
+      for dep in "${deps[@]}"; do
+        dep=${dep// /}
+        scan_metadata "$SCRIPT_DIR/src/modules/$dep.bash"
+        if [[ ${metadatas[${dep}_skip]} == true ]]; then
+          metadatas[${module_name}_skip]=true
+          metadatas[${module_name}_bash]=${metadatas[${dep}_bash]}
+        fi
+      done
+    fi
+
+    if [[ ${metadatas[${module_name}_skip]:-} != true ]]; then
+      metadatas[${module_name}_skip]=false
+      metadatas[${module_name}_bash]="${map[Bash]}"
+    fi
+  fi
+
+  metadatas[${module_name}_path]="$path"
+  metadatas[${module_name}_scanned]=true
+}
+
+scan_metadatas() {
+  local module_name
+  for path in "$SCRIPT_DIR"/src/modules/*.bash; do
+    module_name=$(basename "$path" .bash)
+    _lobash.scan_module_metadata "$module_name"
+  done
+}
+
 generate() {
   write '# This file is generated by https://github.com/adoyle-h/lobash'
   write '# Author: ADoyle <adoyle.h@gmail.com>'
   write '# License: Apache License Version 2.0'
   write "# Version: $VERSION"
   write "# Prefix: $PREFIX"
+  write "# Bash Minimum Version: ${BASH_MIN_VERSION}"
 
-  readarray -t modules < <(find "$SCRIPT_DIR"/src/modules/ -type f -name "*.bash" -exec basename {} .bash \;)
+  local text
+
+  if [[ ${BASH_MIN_VERSION} =~ ^4.(0|1|2|3)$ ]]; then
+    echo -e "${YELLOW}Note: Not all features are supported in Bash ${BASH_MIN_VERSION}.\\nPlease read this link: https://github.com/adoyle-h/lobash/blob/develop/doc/with-lower-version-bash.md${RESET_ALL}"
+    write "#"
+    write "# Note: Not all features are supported in Bash ${BASH_MIN_VERSION}."
+    write "# Please read this link: https://github.com/adoyle-h/lobash/blob/develop/doc/with-lower-version-bash.md"
+  fi
 
   write ''
   write '######################## Lobash Internals ########################'
 
-  # shellcheck source=./src/basic_internals.bash
-  source "$SCRIPT_DIR"/src/basic_internals.bash
+  # shellcheck source=./src/internals/basic_internals.bash
+  source "$SCRIPT_DIR"/src/internals/basic_internals.bash
 
   for name in "${_LOBASH_BASIC_INTERNALS[@]}"; do
     fwrite "$SCRIPT_DIR/src/internals/$name.bash"
   done
   write "_LOBASH_${UNIQ_KEY}_PREFIX=$PREFIX"
   write "_LOBASH_${UNIQ_KEY}_PUBLIC_DEPTH=2"
+  write "_LOBASH_${UNIQ_KEY}_MIN_BASHVER=$BASH_MIN_VERSION"
 
   write ''
   write '######################## Private Methods ########################'
 
+  local compare module_name bashver
+  local -a module_names
+  local -A map skips
+
+  echo "Scanning Module Metadatas..."
   for path in "$SCRIPT_DIR"/src/modules/*.bash; do
-    fwrite "$path"
+    module_name=$(basename "$path" .bash)
+    module_names+=("$module_name")
+    _lobash.scan_module_metadata "$module_name"
+    bashver=$(_lobash.get_module_metadata "$module_name" "Bash")
+    compare=$(semver_compare "$BASH_MIN_VERSION" "$bashver")
+    if (( compare < 0 )); then
+      skips[$module_name]=true
+    fi
+  done
+
+  echo "Writing Module Contents..."
+  for module_name in "${module_names[@]}"; do
+    if [[ -z ${skips[$module_name]:-} ]]; then
+      fwrite "$SCRIPT_DIR/src/modules/$module_name.bash"
+    fi
   done
 
   write ''
   write '######################## Public Methods ########################'
 
-  for module in "${modules[@]}"; do
-    write "$PREFIX$module() { l.${UNIQ_KEY}_$module \"\$@\"; }"
+  echo "Writing Module Public Methods..."
+  for module_name in "${module_names[@]}"; do
+    if [[ -n ${skips[$module_name]:-} ]]; then
+      bashver=$(_lobash.get_module_metadata "$module_name" "Bash")
+      echo -e "${YELLOW}Note${RESET_ALL}: Module '${CYAN}$module_name${RESET_ALL}' is not included in generated file. It supports Bash ${BLUE}${bashver}+${RESET_ALL} while required Bash ${BLUE}$BASH_MIN_VERSION${RESET_ALL}."
+
+      write "# Module '$module_name' is not included in generated file. It supports Bash ${bashver}+ while required Bash $BASH_MIN_VERSION."
+    else
+      write "$PREFIX$module_name() { l.${UNIQ_KEY}_$module_name \"\$@\"; }"
+    fi
   done
 
-  echo "Generated Lobash file: $TARGET"
+  set +u
+  local skip_count=${#skips[@]}
+  echo "Imported $(( ${#module_names[@]} - skip_count )) modules. Skipped ${skip_count} modules."
+  set -u
+  echo -e "Generated Lobash file: ${GREEN}$TARGET${RESET_ALL}"
 }
 
 main() {
