ci: use -d option instead of BUILD_DIST for tools/test-in-docker

diff --git a/test b/test
--- a/test
+++ b/test
@@ -29,6 +29,15 @@ if [[ ${1:-} == '-d' ]]; then
   fi
 
   LOBASH_USE_DIST=true
+elif [[ "${*: -1}" == -d  ]]; then
+  set -- "${@:1:$#-1}"
+
+  if [[ ! -f "$LOBASH_ROOT_DIR/dist/lobash.bash" ]]; then
+    echo "Not found $LOBASH_ROOT_DIR/dist/lobash.bash" >&2
+    exit 2
+  fi
+
+  LOBASH_USE_DIST=true
 fi
 
 if [[ -z "${1:-}" ]]; then
